// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lng")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "São João do Pau d'Alho, Região Imediata de Dracena São Paulo, Região Sudeste, 17970-000, Brasil",
                            Datetime = new DateTime(2024, 7, 30, 22, 2, 0, 0, DateTimeKind.Unspecified),
                            Description = "teste",
                            Image = "https://www.google.com",
                            Lat = -21.2701055,
                            Lng = -51.665497799999997,
                            Title = "Teste"
                        },
                        new
                        {
                            Id = 2,
                            Address = "São João do Pau d'Alho, Região Imediata de Dracena São Paulo, Região Sudeste, 17970-000, Brasil",
                            Datetime = new DateTime(2024, 7, 30, 22, 2, 0, 0, DateTimeKind.Unspecified),
                            Description = "teste 2",
                            Image = "https://www.google.com",
                            Lat = -21.2701055,
                            Lng = -51.665497799999997,
                            Title = "Teste 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
